# src/config.py

# ======================
# GENERAL SETTINGS
# ======================
START_DATE = "2016-01-01"
END_DATE = None  # None = today
HORIZON_DAYS = 5

# ======================
# TRADING PARAMS
# ======================
P_UP_THRESHOLD = 0.52
ROUND_TRIP_COST = 0.001  # 0.10%
SL_ATR_MULT = 1.5

# ======================
# DATA SETTINGS
# ======================
DATA_DIR = "data_cache"

# ======================
# NIFTY 50 (STABLE CORE)
# ======================
# --- Universe (NIFTY 50) ---
NIFTY_50 = [
    "ADANIENT.NS","ADANIPORTS.NS","APOLLOHOSP.NS","ASIANPAINT.NS","AXISBANK.NS",
    "BAJAJ-AUTO.NS","BAJFINANCE.NS","BAJAJFINSV.NS","BPCL.NS","BHARTIARTL.NS",
    "BRITANNIA.NS","CIPLA.NS","COALINDIA.NS","DIVISLAB.NS","DRREDDY.NS",
    "EICHERMOT.NS","GRASIM.NS","HCLTECH.NS","HDFCBANK.NS","HDFCLIFE.NS",
    "HEROMOTOCO.NS","HINDALCO.NS","HINDUNILVR.NS","ICICIBANK.NS","ITC.NS",
    "INDUSINDBK.NS","INFY.NS","JSWSTEEL.NS","KOTAKBANK.NS","LT.NS",
    "LTIM.NS","M&M.NS","MARUTI.NS","NESTLEIND.NS","NTPC.NS",
    "ONGC.NS","POWERGRID.NS","RELIANCE.NS","SBILIFE.NS","SBIN.NS",
    "SUNPHARMA.NS","TATAMOTORS.NS","TATASTEEL.NS","TCS.NS","TECHM.NS",
    "TITAN.NS","ULTRACEMCO.NS","WIPRO.NS"
]


